### ISSUE TITLE
Work hours per day - stats page

### ISSUE THREAD

**Issue by louisLasserre** [enzalito/timeman#16]
- [ ] Select date
- [ ] Desktop
- [ ] Mobile

<img width="296" alt="Screenshot 2024-10-17 at 10 33 47" src="https://github.com/user-attachments/assets/c58838a5-280e-4550-85e7-f74a222f6164">
<img width="433" alt="Screenshot 2024-10-17 at 10 33 41" src="https://github.com/user-attachments/assets/ca2c719c-2dbb-4129-ab1f-df29cdcb4e59">

**Comment by enzalito** [comment]
done by Manon, team mode missing
