### ISSUE TITLE
Clock in - clock out component

### ISSUE THREAD

**Issue by louisLasserre** [enzalito/timeman#2]
<img width="369" alt="Screenshot 2024-10-17 at 09 56 10" src="https://github.com/user-attachments/assets/b8b135b0-8faf-4518-acd3-5c9aaa228dd8">
<img width="464" alt="Screenshot 2024-10-17 at 09 56 06" src="https://github.com/user-attachments/assets/fb6c17b7-fc4d-4bc1-a9b5-f9fdfe366ffd">

**Comment by enzalito** [comment]
done in team overview branch
